name: Update Twitch Clips

on:
  schedule:
    - cron: '0 6 * * *'  # ogni giorno alle 06:00 UTC
  workflow_dispatch:

jobs:
  fetch-and-update:
    runs-on: ubuntu-latest

    steps:
      - name: Clona il repository
        uses: actions/checkout@v3

      - name: Configura Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Installa dipendenze
        run: pip install requests

      - name: Esegui fetch_clips.py
        env:
          TWITCH_CLIENT_ID: ${{ secrets.TWITCH_CLIENT_ID }}
          TWITCH_ACCESS_TOKEN: ${{ secrets.TWITCH_ACCESS_TOKEN }}
        run: python fetch_clips.py

      - name: Commit & Push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "🔄 Update clips.json"
          file_pattern: clips.json
          branch: main
          author_name: github-actions[bot]
          author_email: github-actions[bot]@users.noreply.github.com

